apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: worker
    instanceType: t3a.small
    minSize: 1
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: false
    iam:
      withAddonPolicies:
        autoScaler: true
